package com.icss.model;
// Generated 2016-3-8 18:59:14 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * WuyeBaoxiu generated by hbm2java
 */
public class WuyeBaoxiu implements java.io.Serializable {

	private String id;
	private String xqId;
	private String yonghuId;
	private String baoxiuBiaoti;
	private Integer baoxiuLeixing;
	private Integer baoxiuShijianduan;
	private String baoxiuNeirong;
	private Integer baoxiuZhuangtai;
	private Date baoxiuShijian;
	private Date chuliShijian;
	private Date tijiaoShijian;

	public WuyeBaoxiu() {
	}

	public WuyeBaoxiu(String id) {
		this.id = id;
	}

	public WuyeBaoxiu(String id, String xqId, String yonghuId, String baoxiuBiaoti, Integer baoxiuLeixing,
			Integer baoxiuShijianduan, String baoxiuNeirong, Integer baoxiuZhuangtai, Date baoxiuShijian,
			Date chuliShijian, Date tijiaoShijian) {
		this.id = id;
		this.xqId = xqId;
		this.yonghuId = yonghuId;
		this.baoxiuBiaoti = baoxiuBiaoti;
		this.baoxiuLeixing = baoxiuLeixing;
		this.baoxiuShijianduan = baoxiuShijianduan;
		this.baoxiuNeirong = baoxiuNeirong;
		this.baoxiuZhuangtai = baoxiuZhuangtai;
		this.baoxiuShijian = baoxiuShijian;
		this.chuliShijian = chuliShijian;
		this.tijiaoShijian = tijiaoShijian;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getXqId() {
		return this.xqId;
	}

	public void setXqId(String xqId) {
		this.xqId = xqId;
	}

	public String getYonghuId() {
		return this.yonghuId;
	}

	public void setYonghuId(String yonghuId) {
		this.yonghuId = yonghuId;
	}

	public String getBaoxiuBiaoti() {
		return this.baoxiuBiaoti;
	}

	public void setBaoxiuBiaoti(String baoxiuBiaoti) {
		this.baoxiuBiaoti = baoxiuBiaoti;
	}

	public Integer getBaoxiuLeixing() {
		return this.baoxiuLeixing;
	}

	public void setBaoxiuLeixing(Integer baoxiuLeixing) {
		this.baoxiuLeixing = baoxiuLeixing;
	}

	public Integer getBaoxiuShijianduan() {
		return this.baoxiuShijianduan;
	}

	public void setBaoxiuShijianduan(Integer baoxiuShijianduan) {
		this.baoxiuShijianduan = baoxiuShijianduan;
	}

	public String getBaoxiuNeirong() {
		return this.baoxiuNeirong;
	}

	public void setBaoxiuNeirong(String baoxiuNeirong) {
		this.baoxiuNeirong = baoxiuNeirong;
	}

	public Integer getBaoxiuZhuangtai() {
		return this.baoxiuZhuangtai;
	}

	public void setBaoxiuZhuangtai(Integer baoxiuZhuangtai) {
		this.baoxiuZhuangtai = baoxiuZhuangtai;
	}

	public Date getBaoxiuShijian() {
		return this.baoxiuShijian;
	}

	public void setBaoxiuShijian(Date baoxiuShijian) {
		this.baoxiuShijian = baoxiuShijian;
	}

	public Date getChuliShijian() {
		return this.chuliShijian;
	}

	public void setChuliShijian(Date chuliShijian) {
		this.chuliShijian = chuliShijian;
	}

	public Date getTijiaoShijian() {
		return this.tijiaoShijian;
	}

	public void setTijiaoShijian(Date tijiaoShijian) {
		this.tijiaoShijian = tijiaoShijian;
	}

}
